// challenge-02/frontend/aicare-frontend/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-navbar',
  imports: [],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})

export class NavbarComponent {
  menuOpen = false;
}

<nav class="bg-black p-4 border-b-[1px] border-b-zinc-800 px-10 py-5">
  <div class="w-full h-full flex flex-row justify-between items-center text-center align-middle">
    <div class="flex flex-row gap-x-10 text-center">
      <!-- Logo Container with Hover Effect and Click Event -->
      <div class="flex flex-row items-center cursor-pointer transition-all hover:opacity-80 hover:scale-105"
        (click)="goBack()">
        <!-- Logo Image -->
        <img src="assets/i18n/Images/aicarelogo.png" alt="AICare Logo" class="h-8 mr-2" />
        <!-- Text -->
        <p class="text-white text-2xl font-bold">{{ "AICare" | translate }}</p>
      </div>
    </div>

    <!-- Language Buttons and Search Bar -->
    <div class="flex flex-row items-center gap-4 h-8">
      <!-- PT Button -->
      <button (click)="switchLanguage('pt')"
        [ngClass]="{'bg-white text-black': selectedLanguage === 'pt', 'bg-zinc-950 text-white': selectedLanguage !== 'pt'}"
        class="language-button h-8 text-sm w-14 rounded-[0.175rem] border-zinc-800 hover:shadow-white">
        {{ "PT" | translate }}
      </button>

      <!-- ES Button -->
      <button (click)="switchLanguage('es')"
        [ngClass]="{'bg-white text-black': selectedLanguage === 'es', 'bg-zinc-950 text-white': selectedLanguage !== 'es'}"
        class="language-button h-8 text-sm w-14 rounded-[0.175rem] border-zinc-800 hover:shadow-white">
        {{ "ES" | translate }}
      </button>

      <!-- EN Button -->
      <button (click)="switchLanguage('en')"
        [ngClass]="{'bg-white text-black': selectedLanguage === 'en', 'bg-zinc-950 text-white': selectedLanguage !== 'en'}"
        class="language-button h-8 text-sm w-14 rounded-[0.175rem] border-zinc-800 hover:shadow-white">
        {{ "EN" | translate }}
      </button>



      <!-- Search Bar -->
      <div class="relative">
        <input type="text" [placeholder]="'Search...' | translate"
          class="bg-zinc-900 text-white px-4 py-2 rounded-sm w-48 h-8 outline-none" />
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
          class="w-5 h-5 absolute top-1/2 right-3 transform -translate-y-1/2 text-zinc-700">
          <circle cx="11" cy="11" r="8" stroke-width="2" stroke="currentColor" fill="none"></circle>
          <line x1="21" y1="21" x2="16.65" y2="16.65" stroke-width="2" stroke="currentColor"></line>
        </svg>
      </div>

      <!-- Navigation Links -->
      <div class="flex flex-row h-8 items-center justify-center">
        <ng-container *ngIf="auth.isAuthenticated$ | async; else notLoggedIn">
          <app-logout-button></app-logout-button>
        </ng-container>
        <ng-template #notLoggedIn>
          <app-login-button></app-login-button>
        </ng-template>
      </div>
    </div>
  </div>
</nav>

// gs-improve-vue/src/component/Navbar.vue
<template>
    <div class="flex w-full h-64 md:w-64 md:border-r-2 md:border-r-black md:h-full flex-row md:flex-col">
        <div class="flex-row md:flex-col flex-grow pt-5 overflow-y-auto bg-white">
            <div class="flex items-center flex-shrink-0 px-4">
                <img class="w-auto h-8" src="https://landingfoliocom.imgix.net/store/collection/clarity-dashboard/images/logo.svg" alt="" />
            </div>

            <div class="px-4 mt-8">
                <label for="" class="sr-only"> Search </label>
                <div class="relative">
                    <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                        <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                        </svg>
                    </div>

                    <input type="search" name="" id="" class="block w-full py-2 pl-10 border border-gray-300 rounded-lg focus:ring-indigo-600 focus:border-indigo-600 sm:text-sm" placeholder="Search here" />
                </div>
            </div>

            <div class="px-4 mt-6">
                <hr class="border-gray-200" />
            </div>

            <div class="flex flex-row md:flex-col flex-1 px-3 mt-6">
                <div class="space-y-4 flex flex-row md:flex-col">
                    <nav class="flex-1 space-y-2 flex flex-row md:flex-col">
                        <a href="#" title="" class="flex items-center px-4 py-2.5 text-sm font-medium text-white transition-all duration-200 bg-indigo-600 rounded-lg group">
                            
                            Page 1
                        </a>

                        <a href="#" class="flex items-center px-4 py-2.5 text-sm font-medium transition-all duration-200 text-gray-900 hover:text-white rounded-lg hover:bg-indigo-600 group">
                            
                            Page 2
                        </a>

                        
                    </nav>

                    
                 
                </div>

                
            </div>
        </div>
    </div>
</template>

<script>
export default {

}
</script>

<style>

</style>
